// Comprehensive Spanish grocery database
// Organized by supermarket sections

export interface GroceryProduct {
  name: string;
  category: string;
  subcategory?: string;
  brand?: string;
}

export const GROCERY_CATEGORIES = [
  "Frutas y Verduras",
  "Lácteos",
  "Carnes y Mariscos",
  "Panadería",
  "Despensa",
  "Congelados",
  "Bebidas",
  "Comida Preparada",
  "Droguería",
  "Otros",
] as const;

export const spanishGroceries: GroceryProduct[] = [
  // ============================================
  // FRUTAS Y VERDURAS
  // ============================================
  
  // Frutas
  { name: "Manzanas", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Manzana Golden", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Manzana Fuji", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Manzana Granny Smith", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Plátanos", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Plátano de Canarias", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Naranjas", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Naranjas de zumo", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Naranjas de mesa", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Mandarinas", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Clementinas", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Limones", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Limas", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Pomelo", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Fresas", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Frambuesas", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Arándanos", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Moras", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Uvas blancas", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Uvas negras", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Uvas sin pepitas", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Sandía", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Melón", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Melón Piel de Sapo", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Melón Cantalupo", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Piña", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Mango", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Papaya", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Kiwi", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Kiwi amarillo", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Aguacate", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Pera", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Pera Conferencia", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Melocotón", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Nectarina", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Ciruelas", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Albaricoques", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Cerezas", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Granada", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Higos", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Coco", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Maracuyá", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Chirimoya", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Caqui", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Nísperos", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Lichis", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Dátiles", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Membrillo", category: "Frutas y Verduras", subcategory: "Frutas" },

  // Verduras y Hortalizas
  { name: "Tomates", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Tomates pera", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Tomates cherry", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Tomate Raf", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Tomate rama", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Tomate kumato", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Cebolla", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Cebolla morada", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Cebolla dulce", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Cebolleta", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Cebollino", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Puerro", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Ajo", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Ajo negro", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Patatas", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Patata nueva", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Patatas para freír", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Boniato", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Zanahoria", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Calabacín", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Calabaza", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Berenjena", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Pepino", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Pimiento rojo", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Pimiento verde", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Pimiento amarillo", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Pimiento del piquillo", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Pimiento de padrón", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Chile jalapeño", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Guindilla", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Lechuga", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Lechuga romana", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Lechuga iceberg", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Lechuga batavia", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Escarola", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Rúcula", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Espinacas", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Espinacas baby", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Canónigos", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Acelgas", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Brócoli", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Coliflor", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Col lombarda", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Repollo", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Coles de Bruselas", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Col kale", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Apio", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Hinojo", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Alcachofa", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Espárragos verdes", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Espárragos blancos", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Judías verdes", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Guisantes", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Habas", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Remolacha", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Rábanos", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Nabo", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Champiñones", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Champiñones Portobello", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Setas variadas", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Jengibre", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Maíz dulce", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Endivias", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Berros", category: "Frutas y Verduras", subcategory: "Verduras" },
  
  // Hierbas frescas
  { name: "Perejil fresco", category: "Frutas y Verduras", subcategory: "Hierbas" },
  { name: "Cilantro fresco", category: "Frutas y Verduras", subcategory: "Hierbas" },
  { name: "Albahaca fresca", category: "Frutas y Verduras", subcategory: "Hierbas" },
  { name: "Menta fresca", category: "Frutas y Verduras", subcategory: "Hierbas" },
  { name: "Hierbabuena", category: "Frutas y Verduras", subcategory: "Hierbas" },
  { name: "Romero fresco", category: "Frutas y Verduras", subcategory: "Hierbas" },
  { name: "Tomillo fresco", category: "Frutas y Verduras", subcategory: "Hierbas" },
  { name: "Orégano fresco", category: "Frutas y Verduras", subcategory: "Hierbas" },
  { name: "Eneldo fresco", category: "Frutas y Verduras", subcategory: "Hierbas" },
  { name: "Laurel fresco", category: "Frutas y Verduras", subcategory: "Hierbas" },
  { name: "Salvia fresca", category: "Frutas y Verduras", subcategory: "Hierbas" },

  // ============================================
  // LÁCTEOS Y HUEVOS
  // ============================================
  
  // Leche
  { name: "Leche entera", category: "Lácteos", subcategory: "Leche" },
  { name: "Leche semidesnatada", category: "Lácteos", subcategory: "Leche" },
  { name: "Leche desnatada", category: "Lácteos", subcategory: "Leche" },
  { name: "Leche sin lactosa", category: "Lácteos", subcategory: "Leche" },
  { name: "Leche de avena", category: "Lácteos", subcategory: "Leche vegetal" },
  { name: "Leche de almendra", category: "Lácteos", subcategory: "Leche vegetal" },
  { name: "Leche de soja", category: "Lácteos", subcategory: "Leche vegetal" },
  { name: "Leche de coco", category: "Lácteos", subcategory: "Leche vegetal" },
  { name: "Leche de arroz", category: "Lácteos", subcategory: "Leche vegetal" },
  { name: "Nata líquida para cocinar", category: "Lácteos", subcategory: "Nata" },
  { name: "Nata para montar", category: "Lácteos", subcategory: "Nata" },
  { name: "Nata ligera", category: "Lácteos", subcategory: "Nata" },
  { name: "Nata montada en spray", category: "Lácteos", subcategory: "Nata" },
  { name: "Leche condensada", category: "Lácteos", subcategory: "Leche" },
  { name: "Leche evaporada", category: "Lácteos", subcategory: "Leche" },

  // Yogures
  { name: "Yogur natural", category: "Lácteos", subcategory: "Yogures" },
  { name: "Yogur griego", category: "Lácteos", subcategory: "Yogures" },
  { name: "Yogur de fresa", category: "Lácteos", subcategory: "Yogures" },
  { name: "Yogur de frutas", category: "Lácteos", subcategory: "Yogures" },
  { name: "Yogur desnatado", category: "Lácteos", subcategory: "Yogures" },
  { name: "Yogur líquido", category: "Lácteos", subcategory: "Yogures" },
  { name: "Kéfir", category: "Lácteos", subcategory: "Yogures" },
  { name: "Skyr", category: "Lácteos", subcategory: "Yogures" },
  { name: "Yogur bifidus", category: "Lácteos", subcategory: "Yogures" },

  // Quesos
  { name: "Queso manchego", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso manchego curado", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso manchego semicurado", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso fresco", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso de Burgos", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso tierno", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso rallado", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso mozzarella", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso mozzarella fresca", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso parmesano", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso emmental", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso gouda", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso cheddar", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso brie", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso camembert", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso azul", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso roquefort", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso gorgonzola", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso cabrales", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso de cabra", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso feta", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso crema", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso Philadelphia", category: "Lácteos", subcategory: "Quesos", brand: "Philadelphia" },
  { name: "Queso mascarpone", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso ricotta", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso en lonchas", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso para hamburguesas", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso tetilla", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso idiazábal", category: "Lácteos", subcategory: "Quesos" },
  { name: "Burrata", category: "Lácteos", subcategory: "Quesos" },
  { name: "Requesón", category: "Lácteos", subcategory: "Quesos" },

  // Mantequilla y margarina
  { name: "Mantequilla", category: "Lácteos", subcategory: "Mantequillas" },
  { name: "Mantequilla sin sal", category: "Lácteos", subcategory: "Mantequillas" },
  { name: "Mantequilla con sal", category: "Lácteos", subcategory: "Mantequillas" },
  { name: "Mantequilla ligera", category: "Lácteos", subcategory: "Mantequillas" },
  { name: "Margarina", category: "Lácteos", subcategory: "Mantequillas" },

  // Huevos
  { name: "Huevos (docena)", category: "Lácteos", subcategory: "Huevos" },
  { name: "Huevos (media docena)", category: "Lácteos", subcategory: "Huevos" },
  { name: "Huevos camperos", category: "Lácteos", subcategory: "Huevos" },
  { name: "Huevos ecológicos", category: "Lácteos", subcategory: "Huevos" },
  { name: "Huevos de codorniz", category: "Lácteos", subcategory: "Huevos" },
  { name: "Claras de huevo", category: "Lácteos", subcategory: "Huevos" },

  // Otros lácteos
  { name: "Cuajada", category: "Lácteos", subcategory: "Postres lácteos" },
  { name: "Natillas", category: "Lácteos", subcategory: "Postres lácteos" },
  { name: "Flan", category: "Lácteos", subcategory: "Postres lácteos" },
  { name: "Arroz con leche", category: "Lácteos", subcategory: "Postres lácteos" },
  { name: "Crema catalana", category: "Lácteos", subcategory: "Postres lácteos" },
  { name: "Mousse de chocolate", category: "Lácteos", subcategory: "Postres lácteos" },

  // ============================================
  // CARNES Y MARISCOS
  // ============================================
  
  // Pollo
  { name: "Pechuga de pollo", category: "Carnes y Mariscos", subcategory: "Aves" },
  { name: "Muslos de pollo", category: "Carnes y Mariscos", subcategory: "Aves" },
  { name: "Contramuslos de pollo", category: "Carnes y Mariscos", subcategory: "Aves" },
  { name: "Pollo entero", category: "Carnes y Mariscos", subcategory: "Aves" },
  { name: "Alitas de pollo", category: "Carnes y Mariscos", subcategory: "Aves" },
  { name: "Pollo troceado", category: "Carnes y Mariscos", subcategory: "Aves" },
  { name: "Pollo asado", category: "Carnes y Mariscos", subcategory: "Aves" },
  { name: "Pechuga de pavo", category: "Carnes y Mariscos", subcategory: "Aves" },
  { name: "Muslos de pavo", category: "Carnes y Mariscos", subcategory: "Aves" },
  { name: "Pavo en filetes", category: "Carnes y Mariscos", subcategory: "Aves" },

  // Cerdo
  { name: "Lomo de cerdo", category: "Carnes y Mariscos", subcategory: "Cerdo" },
  { name: "Solomillo de cerdo", category: "Carnes y Mariscos", subcategory: "Cerdo" },
  { name: "Chuletas de cerdo", category: "Carnes y Mariscos", subcategory: "Cerdo" },
  { name: "Costillas de cerdo", category: "Carnes y Mariscos", subcategory: "Cerdo" },
  { name: "Secreto ibérico", category: "Carnes y Mariscos", subcategory: "Cerdo" },
  { name: "Pluma ibérica", category: "Carnes y Mariscos", subcategory: "Cerdo" },
  { name: "Presa ibérica", category: "Carnes y Mariscos", subcategory: "Cerdo" },
  { name: "Carrillada de cerdo", category: "Carnes y Mariscos", subcategory: "Cerdo" },
  { name: "Panceta", category: "Carnes y Mariscos", subcategory: "Cerdo" },
  { name: "Tocino", category: "Carnes y Mariscos", subcategory: "Cerdo" },
  { name: "Bacon", category: "Carnes y Mariscos", subcategory: "Cerdo" },
  { name: "Bacon ahumado", category: "Carnes y Mariscos", subcategory: "Cerdo" },
  { name: "Jamón serrano", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Jamón ibérico", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Jamón cocido", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Jamón york", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Chorizo", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Chorizo picante", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Chorizo dulce", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Salchichón", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Fuet", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Lomo embuchado", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Morcilla", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Salchichas frescas", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Salchichas Frankfurt", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Butifarra", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Sobrasada", category: "Carnes y Mariscos", subcategory: "Embutidos" },

  // Ternera
  { name: "Filete de ternera", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Solomillo de ternera", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Entrecot de ternera", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Chuletón de ternera", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Ternera para guisar", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Carne picada de ternera", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Carne picada mixta", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Hamburguesas de ternera", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Albóndigas", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Ossobuco", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Rabo de toro", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Morcillo de ternera", category: "Carnes y Mariscos", subcategory: "Ternera" },

  // Cordero
  { name: "Chuletas de cordero", category: "Carnes y Mariscos", subcategory: "Cordero" },
  { name: "Pierna de cordero", category: "Carnes y Mariscos", subcategory: "Cordero" },
  { name: "Paletilla de cordero", category: "Carnes y Mariscos", subcategory: "Cordero" },
  { name: "Cordero para guisar", category: "Carnes y Mariscos", subcategory: "Cordero" },

  // Conejo
  { name: "Conejo entero", category: "Carnes y Mariscos", subcategory: "Otros" },
  { name: "Conejo troceado", category: "Carnes y Mariscos", subcategory: "Otros" },

  // Pescados
  { name: "Salmón fresco", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Salmón ahumado", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Lomos de salmón", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Trucha", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Lubina", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Dorada", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Merluza", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Merluza en filetes", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Merluza en rodajas", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Bacalao fresco", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Bacalao salado", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Bacalao desalado", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Rape", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Atún fresco", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Bonito del norte", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Caballa", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Sardinas", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Boquerones", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Anchoas", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Lenguado", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Rodaballo", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Emperador", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Pez espada", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Tilapia", category: "Carnes y Mariscos", subcategory: "Pescados" },

  // Mariscos
  { name: "Gambas", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Gambas peladas", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Gambón", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Langostinos", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Camarones", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Mejillones", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Almejas", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Berberechos", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Calamares", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Anillas de calamar", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Pulpo", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Sepia", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Chipirón", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Vieiras", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Cigalas", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Nécoras", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Centollo", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Bogavante", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Langosta", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Percebes", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Surimi (palitos de cangrejo)", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Cocktail de marisco", category: "Carnes y Mariscos", subcategory: "Mariscos" },

  // ============================================
  // PANADERÍA
  // ============================================
  { name: "Pan de barra", category: "Panadería", subcategory: "Pan" },
  { name: "Baguette", category: "Panadería", subcategory: "Pan" },
  { name: "Pan de molde", category: "Panadería", subcategory: "Pan" },
  { name: "Pan de molde integral", category: "Panadería", subcategory: "Pan" },
  { name: "Pan de molde sin corteza", category: "Panadería", subcategory: "Pan" },
  { name: "Pan de centeno", category: "Panadería", subcategory: "Pan" },
  { name: "Pan integral", category: "Panadería", subcategory: "Pan" },
  { name: "Pan sin gluten", category: "Panadería", subcategory: "Pan" },
  { name: "Pan de hamburguesa", category: "Panadería", subcategory: "Pan" },
  { name: "Pan de hot dog", category: "Panadería", subcategory: "Pan" },
  { name: "Panecillos", category: "Panadería", subcategory: "Pan" },
  { name: "Chapata", category: "Panadería", subcategory: "Pan" },
  { name: "Pan rústico", category: "Panadería", subcategory: "Pan" },
  { name: "Pan de pueblo", category: "Panadería", subcategory: "Pan" },
  { name: "Pan rallado", category: "Panadería", subcategory: "Pan" },
  { name: "Pan rallado panko", category: "Panadería", subcategory: "Pan" },
  { name: "Picatostes", category: "Panadería", subcategory: "Pan" },
  { name: "Tostadas", category: "Panadería", subcategory: "Pan" },
  { name: "Colines", category: "Panadería", subcategory: "Pan" },
  { name: "Picos", category: "Panadería", subcategory: "Pan" },
  { name: "Regañás", category: "Panadería", subcategory: "Pan" },
  { name: "Tortillas de trigo", category: "Panadería", subcategory: "Pan" },
  { name: "Tortillas de maíz", category: "Panadería", subcategory: "Pan" },
  { name: "Wraps", category: "Panadería", subcategory: "Pan" },
  { name: "Pan de pita", category: "Panadería", subcategory: "Pan" },
  { name: "Pan naan", category: "Panadería", subcategory: "Pan" },
  { name: "Croissants", category: "Panadería", subcategory: "Bollería" },
  { name: "Croissants de chocolate", category: "Panadería", subcategory: "Bollería" },
  { name: "Napolitanas", category: "Panadería", subcategory: "Bollería" },
  { name: "Ensaimadas", category: "Panadería", subcategory: "Bollería" },
  { name: "Magdalenas", category: "Panadería", subcategory: "Bollería" },
  { name: "Sobaos", category: "Panadería", subcategory: "Bollería" },
  { name: "Donuts", category: "Panadería", subcategory: "Bollería" },
  { name: "Palmeras", category: "Panadería", subcategory: "Bollería" },
  { name: "Bizcocho", category: "Panadería", subcategory: "Bollería" },

  // ============================================
  // DESPENSA
  // ============================================
  
  // Aceites y vinagres
  { name: "Aceite de oliva virgen extra", category: "Despensa", subcategory: "Aceites" },
  { name: "Aceite de oliva", category: "Despensa", subcategory: "Aceites" },
  { name: "Aceite de oliva suave", category: "Despensa", subcategory: "Aceites" },
  { name: "Aceite de girasol", category: "Despensa", subcategory: "Aceites" },
  { name: "Aceite de coco", category: "Despensa", subcategory: "Aceites" },
  { name: "Aceite de sésamo", category: "Despensa", subcategory: "Aceites" },
  { name: "Vinagre de vino", category: "Despensa", subcategory: "Vinagres" },
  { name: "Vinagre balsámico", category: "Despensa", subcategory: "Vinagres" },
  { name: "Vinagre de manzana", category: "Despensa", subcategory: "Vinagres" },
  { name: "Vinagre de Jerez", category: "Despensa", subcategory: "Vinagres" },
  { name: "Vinagre de Módena", category: "Despensa", subcategory: "Vinagres" },

  // Pasta y arroz
  { name: "Espaguetis", category: "Despensa", subcategory: "Pasta" },
  { name: "Macarrones", category: "Despensa", subcategory: "Pasta" },
  { name: "Penne", category: "Despensa", subcategory: "Pasta" },
  { name: "Fusilli", category: "Despensa", subcategory: "Pasta" },
  { name: "Tallarines", category: "Despensa", subcategory: "Pasta" },
  { name: "Tagliatelle", category: "Despensa", subcategory: "Pasta" },
  { name: "Fettuccine", category: "Despensa", subcategory: "Pasta" },
  { name: "Lasaña (placas)", category: "Despensa", subcategory: "Pasta" },
  { name: "Canelones (placas)", category: "Despensa", subcategory: "Pasta" },
  { name: "Fideos", category: "Despensa", subcategory: "Pasta" },
  { name: "Fideos cabello de ángel", category: "Despensa", subcategory: "Pasta" },
  { name: "Pasta integral", category: "Despensa", subcategory: "Pasta" },
  { name: "Pasta sin gluten", category: "Despensa", subcategory: "Pasta" },
  { name: "Ñoquis", category: "Despensa", subcategory: "Pasta" },
  { name: "Raviolis", category: "Despensa", subcategory: "Pasta" },
  { name: "Tortellini", category: "Despensa", subcategory: "Pasta" },
  { name: "Cous cous", category: "Despensa", subcategory: "Pasta" },
  { name: "Fideos de arroz", category: "Despensa", subcategory: "Pasta" },
  { name: "Noodles", category: "Despensa", subcategory: "Pasta" },
  { name: "Arroz redondo", category: "Despensa", subcategory: "Arroz" },
  { name: "Arroz bomba", category: "Despensa", subcategory: "Arroz" },
  { name: "Arroz largo", category: "Despensa", subcategory: "Arroz" },
  { name: "Arroz basmati", category: "Despensa", subcategory: "Arroz" },
  { name: "Arroz integral", category: "Despensa", subcategory: "Arroz" },
  { name: "Arroz para sushi", category: "Despensa", subcategory: "Arroz" },
  { name: "Arroz salvaje", category: "Despensa", subcategory: "Arroz" },
  { name: "Arroz vaporizado", category: "Despensa", subcategory: "Arroz" },

  // Legumbres
  { name: "Garbanzos (bote)", category: "Despensa", subcategory: "Legumbres" },
  { name: "Garbanzos secos", category: "Despensa", subcategory: "Legumbres" },
  { name: "Lentejas (bote)", category: "Despensa", subcategory: "Legumbres" },
  { name: "Lentejas secas", category: "Despensa", subcategory: "Legumbres" },
  { name: "Lentejas pardinas", category: "Despensa", subcategory: "Legumbres" },
  { name: "Alubias blancas", category: "Despensa", subcategory: "Legumbres" },
  { name: "Alubias rojas", category: "Despensa", subcategory: "Legumbres" },
  { name: "Judías pintas", category: "Despensa", subcategory: "Legumbres" },
  { name: "Judías negras", category: "Despensa", subcategory: "Legumbres" },
  { name: "Habas secas", category: "Despensa", subcategory: "Legumbres" },
  { name: "Edamame", category: "Despensa", subcategory: "Legumbres" },

  // Conservas
  { name: "Tomate triturado", category: "Despensa", subcategory: "Conservas" },
  { name: "Tomate frito", category: "Despensa", subcategory: "Conservas" },
  { name: "Tomate natural (lata)", category: "Despensa", subcategory: "Conservas" },
  { name: "Tomate concentrado", category: "Despensa", subcategory: "Conservas" },
  { name: "Atún en aceite", category: "Despensa", subcategory: "Conservas" },
  { name: "Atún al natural", category: "Despensa", subcategory: "Conservas" },
  { name: "Atún en escabeche", category: "Despensa", subcategory: "Conservas" },
  { name: "Sardinas en aceite", category: "Despensa", subcategory: "Conservas" },
  { name: "Caballa en aceite", category: "Despensa", subcategory: "Conservas" },
  { name: "Bonito del norte (lata)", category: "Despensa", subcategory: "Conservas" },
  { name: "Anchoas en aceite", category: "Despensa", subcategory: "Conservas" },
  { name: "Mejillones en escabeche", category: "Despensa", subcategory: "Conservas" },
  { name: "Berberechos al natural", category: "Despensa", subcategory: "Conservas" },
  { name: "Maíz dulce (lata)", category: "Despensa", subcategory: "Conservas" },
  { name: "Guisantes (lata)", category: "Despensa", subcategory: "Conservas" },
  { name: "Champiñones laminados", category: "Despensa", subcategory: "Conservas" },
  { name: "Espárragos blancos (lata)", category: "Despensa", subcategory: "Conservas" },
  { name: "Pimientos del piquillo (lata)", category: "Despensa", subcategory: "Conservas" },
  { name: "Pimientos morrones", category: "Despensa", subcategory: "Conservas" },
  { name: "Aceitunas verdes", category: "Despensa", subcategory: "Conservas" },
  { name: "Aceitunas negras", category: "Despensa", subcategory: "Conservas" },
  { name: "Aceitunas rellenas de anchoa", category: "Despensa", subcategory: "Conservas" },
  { name: "Pepinillos", category: "Despensa", subcategory: "Conservas" },
  { name: "Alcaparras", category: "Despensa", subcategory: "Conservas" },
  { name: "Cebollitas encurtidas", category: "Despensa", subcategory: "Conservas" },
  { name: "Palmitos", category: "Despensa", subcategory: "Conservas" },
  { name: "Corazones de alcachofa", category: "Despensa", subcategory: "Conservas" },
  { name: "Piña en almíbar", category: "Despensa", subcategory: "Conservas" },
  { name: "Melocotón en almíbar", category: "Despensa", subcategory: "Conservas" },
  { name: "Coco rallado", category: "Despensa", subcategory: "Conservas" },

  // Salsas y condimentos
  { name: "Mayonesa", category: "Despensa", subcategory: "Salsas" },
  { name: "Ketchup", category: "Despensa", subcategory: "Salsas" },
  { name: "Mostaza", category: "Despensa", subcategory: "Salsas" },
  { name: "Mostaza de Dijon", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa barbacoa", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa de soja", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa teriyaki", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa Worcestershire", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa sriracha", category: "Despensa", subcategory: "Salsas" },
  { name: "Tabasco", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa picante", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa césar", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa pesto", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa carbonara", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa boloñesa", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa de tomate para pasta", category: "Despensa", subcategory: "Salsas" },
  { name: "Hummus", category: "Despensa", subcategory: "Salsas" },
  { name: "Guacamole", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa alioli", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa brava", category: "Despensa", subcategory: "Salsas" },
  { name: "Tahini", category: "Despensa", subcategory: "Salsas" },

  // Especias y condimentos
  { name: "Sal", category: "Despensa", subcategory: "Especias" },
  { name: "Sal marina", category: "Despensa", subcategory: "Especias" },
  { name: "Sal del Himalaya", category: "Despensa", subcategory: "Especias" },
  { name: "Pimienta negra", category: "Despensa", subcategory: "Especias" },
  { name: "Pimienta blanca", category: "Despensa", subcategory: "Especias" },
  { name: "Pimentón dulce", category: "Despensa", subcategory: "Especias" },
  { name: "Pimentón picante", category: "Despensa", subcategory: "Especias" },
  { name: "Pimentón de la Vera", category: "Despensa", subcategory: "Especias" },
  { name: "Orégano seco", category: "Despensa", subcategory: "Especias" },
  { name: "Tomillo seco", category: "Despensa", subcategory: "Especias" },
  { name: "Romero seco", category: "Despensa", subcategory: "Especias" },
  { name: "Albahaca seca", category: "Despensa", subcategory: "Especias" },
  { name: "Laurel", category: "Despensa", subcategory: "Especias" },
  { name: "Comino", category: "Despensa", subcategory: "Especias" },
  { name: "Cúrcuma", category: "Despensa", subcategory: "Especias" },
  { name: "Curry", category: "Despensa", subcategory: "Especias" },
  { name: "Canela en rama", category: "Despensa", subcategory: "Especias" },
  { name: "Canela molida", category: "Despensa", subcategory: "Especias" },
  { name: "Nuez moscada", category: "Despensa", subcategory: "Especias" },
  { name: "Clavo", category: "Despensa", subcategory: "Especias" },
  { name: "Azafrán", category: "Despensa", subcategory: "Especias" },
  { name: "Colorante alimentario", category: "Despensa", subcategory: "Especias" },
  { name: "Ajo en polvo", category: "Despensa", subcategory: "Especias" },
  { name: "Cebolla en polvo", category: "Despensa", subcategory: "Especias" },
  { name: "Cayena", category: "Despensa", subcategory: "Especias" },
  { name: "Jengibre molido", category: "Despensa", subcategory: "Especias" },
  { name: "Hierbas provenzales", category: "Despensa", subcategory: "Especias" },
  { name: "Sazonador para pollo", category: "Despensa", subcategory: "Especias" },
  { name: "Sazonador para carne", category: "Despensa", subcategory: "Especias" },
  { name: "Sazonador para pescado", category: "Despensa", subcategory: "Especias" },

  // Harinas y repostería
  { name: "Harina de trigo", category: "Despensa", subcategory: "Harinas" },
  { name: "Harina de repostería", category: "Despensa", subcategory: "Harinas" },
  { name: "Harina de fuerza", category: "Despensa", subcategory: "Harinas" },
  { name: "Harina integral", category: "Despensa", subcategory: "Harinas" },
  { name: "Harina de maíz", category: "Despensa", subcategory: "Harinas" },
  { name: "Maicena", category: "Despensa", subcategory: "Harinas" },
  { name: "Harina de almendra", category: "Despensa", subcategory: "Harinas" },
  { name: "Harina de avena", category: "Despensa", subcategory: "Harinas" },
  { name: "Harina sin gluten", category: "Despensa", subcategory: "Harinas" },
  { name: "Levadura fresca", category: "Despensa", subcategory: "Repostería" },
  { name: "Levadura seca", category: "Despensa", subcategory: "Repostería" },
  { name: "Levadura química", category: "Despensa", subcategory: "Repostería" },
  { name: "Bicarbonato", category: "Despensa", subcategory: "Repostería" },
  { name: "Azúcar blanco", category: "Despensa", subcategory: "Repostería" },
  { name: "Azúcar moreno", category: "Despensa", subcategory: "Repostería" },
  { name: "Azúcar glass", category: "Despensa", subcategory: "Repostería" },
  { name: "Panela", category: "Despensa", subcategory: "Repostería" },
  { name: "Miel", category: "Despensa", subcategory: "Repostería" },
  { name: "Sirope de arce", category: "Despensa", subcategory: "Repostería" },
  { name: "Sirope de agave", category: "Despensa", subcategory: "Repostería" },
  { name: "Cacao puro en polvo", category: "Despensa", subcategory: "Repostería" },
  { name: "Chocolate negro", category: "Despensa", subcategory: "Repostería" },
  { name: "Chocolate con leche", category: "Despensa", subcategory: "Repostería" },
  { name: "Chocolate blanco", category: "Despensa", subcategory: "Repostería" },
  { name: "Pepitas de chocolate", category: "Despensa", subcategory: "Repostería" },
  { name: "Extracto de vainilla", category: "Despensa", subcategory: "Repostería" },
  { name: "Esencia de almendra", category: "Despensa", subcategory: "Repostería" },
  { name: "Masa de hojaldre", category: "Despensa", subcategory: "Repostería" },
  { name: "Masa quebrada", category: "Despensa", subcategory: "Repostería" },
  { name: "Masa de pizza", category: "Despensa", subcategory: "Repostería" },
  { name: "Gelatina en polvo", category: "Despensa", subcategory: "Repostería" },
  { name: "Gelatina en láminas", category: "Despensa", subcategory: "Repostería" },

  // Frutos secos y semillas
  { name: "Almendras", category: "Despensa", subcategory: "Frutos secos" },
  { name: "Almendras laminadas", category: "Despensa", subcategory: "Frutos secos" },
  { name: "Almendras molidas", category: "Despensa", subcategory: "Frutos secos" },
  { name: "Nueces", category: "Despensa", subcategory: "Frutos secos" },
  { name: "Avellanas", category: "Despensa", subcategory: "Frutos secos" },
  { name: "Pistachos", category: "Despensa", subcategory: "Frutos secos" },
  { name: "Cacahuetes", category: "Despensa", subcategory: "Frutos secos" },
  { name: "Anacardos", category: "Despensa", subcategory: "Frutos secos" },
  { name: "Piñones", category: "Despensa", subcategory: "Frutos secos" },
  { name: "Castañas", category: "Despensa", subcategory: "Frutos secos" },
  { name: "Mix de frutos secos", category: "Despensa", subcategory: "Frutos secos" },
  { name: "Pasas", category: "Despensa", subcategory: "Frutos secos" },
  { name: "Orejones", category: "Despensa", subcategory: "Frutos secos" },
  { name: "Ciruelas pasas", category: "Despensa", subcategory: "Frutos secos" },
  { name: "Arándanos secos", category: "Despensa", subcategory: "Frutos secos" },
  { name: "Semillas de girasol", category: "Despensa", subcategory: "Semillas" },
  { name: "Semillas de calabaza", category: "Despensa", subcategory: "Semillas" },
  { name: "Semillas de chía", category: "Despensa", subcategory: "Semillas" },
  { name: "Semillas de lino", category: "Despensa", subcategory: "Semillas" },
  { name: "Semillas de sésamo", category: "Despensa", subcategory: "Semillas" },
  { name: "Semillas de amapola", category: "Despensa", subcategory: "Semillas" },

  // Cereales y desayuno
  { name: "Copos de avena", category: "Despensa", subcategory: "Cereales" },
  { name: "Muesli", category: "Despensa", subcategory: "Cereales" },
  { name: "Granola", category: "Despensa", subcategory: "Cereales" },
  { name: "Cereales de desayuno", category: "Despensa", subcategory: "Cereales" },
  { name: "Corn flakes", category: "Despensa", subcategory: "Cereales" },
  { name: "Special K", category: "Despensa", subcategory: "Cereales" },
  { name: "Quinoa", category: "Despensa", subcategory: "Cereales" },
  { name: "Bulgur", category: "Despensa", subcategory: "Cereales" },
  { name: "Trigo sarraceno", category: "Despensa", subcategory: "Cereales" },
  { name: "Polenta", category: "Despensa", subcategory: "Cereales" },

  // Caldos y sopas
  { name: "Caldo de pollo", category: "Despensa", subcategory: "Caldos" },
  { name: "Caldo de carne", category: "Despensa", subcategory: "Caldos" },
  { name: "Caldo de verduras", category: "Despensa", subcategory: "Caldos" },
  { name: "Caldo de pescado", category: "Despensa", subcategory: "Caldos" },
  { name: "Pastillas de caldo", category: "Despensa", subcategory: "Caldos" },
  { name: "Sopa de sobre", category: "Despensa", subcategory: "Caldos" },
  { name: "Gazpacho", category: "Despensa", subcategory: "Caldos" },
  { name: "Salmorejo", category: "Despensa", subcategory: "Caldos" },

  // Cremas para untar
  { name: "Crema de cacahuete", category: "Despensa", subcategory: "Cremas" },
  { name: "Nocilla", category: "Despensa", subcategory: "Cremas", brand: "Nocilla" },
  { name: "Nutella", category: "Despensa", subcategory: "Cremas", brand: "Nutella" },
  { name: "Crema de cacao", category: "Despensa", subcategory: "Cremas" },
  { name: "Mermelada de fresa", category: "Despensa", subcategory: "Cremas" },
  { name: "Mermelada de melocotón", category: "Despensa", subcategory: "Cremas" },
  { name: "Mermelada de naranja", category: "Despensa", subcategory: "Cremas" },
  { name: "Mermelada de arándanos", category: "Despensa", subcategory: "Cremas" },
  { name: "Mermelada sin azúcar", category: "Despensa", subcategory: "Cremas" },
  { name: "Dulce de membrillo", category: "Despensa", subcategory: "Cremas" },

  // ============================================
  // CONGELADOS
  // ============================================
  { name: "Verduras congeladas", category: "Congelados", subcategory: "Verduras" },
  { name: "Judías verdes congeladas", category: "Congelados", subcategory: "Verduras" },
  { name: "Guisantes congelados", category: "Congelados", subcategory: "Verduras" },
  { name: "Espinacas congeladas", category: "Congelados", subcategory: "Verduras" },
  { name: "Brócoli congelado", category: "Congelados", subcategory: "Verduras" },
  { name: "Menestra congelada", category: "Congelados", subcategory: "Verduras" },
  { name: "Salteado de verduras", category: "Congelados", subcategory: "Verduras" },
  { name: "Patatas congeladas", category: "Congelados", subcategory: "Verduras" },
  { name: "Patatas fritas congeladas", category: "Congelados", subcategory: "Verduras" },
  { name: "Cebolla congelada", category: "Congelados", subcategory: "Verduras" },
  { name: "Pimiento congelado", category: "Congelados", subcategory: "Verduras" },
  { name: "Frutas congeladas", category: "Congelados", subcategory: "Frutas" },
  { name: "Frutos rojos congelados", category: "Congelados", subcategory: "Frutas" },
  { name: "Mango congelado", category: "Congelados", subcategory: "Frutas" },
  { name: "Gambas congeladas", category: "Congelados", subcategory: "Pescados" },
  { name: "Langostinos congelados", category: "Congelados", subcategory: "Pescados" },
  { name: "Calamares congelados", category: "Congelados", subcategory: "Pescados" },
  { name: "Mejillones congelados", category: "Congelados", subcategory: "Pescados" },
  { name: "Cocktail de mariscos congelado", category: "Congelados", subcategory: "Pescados" },
  { name: "Pescado empanado", category: "Congelados", subcategory: "Pescados" },
  { name: "Varitas de merluza", category: "Congelados", subcategory: "Pescados" },
  { name: "Lomos de bacalao congelado", category: "Congelados", subcategory: "Pescados" },
  { name: "Filetes de merluza congelados", category: "Congelados", subcategory: "Pescados" },
  { name: "Pollo congelado", category: "Congelados", subcategory: "Carnes" },
  { name: "Nuggets de pollo", category: "Congelados", subcategory: "Carnes" },
  { name: "Hamburguesas congeladas", category: "Congelados", subcategory: "Carnes" },
  { name: "Salchichas congeladas", category: "Congelados", subcategory: "Carnes" },
  { name: "Pizza congelada", category: "Congelados", subcategory: "Preparados" },
  { name: "Lasaña congelada", category: "Congelados", subcategory: "Preparados" },
  { name: "Canelones congelados", category: "Congelados", subcategory: "Preparados" },
  { name: "Croquetas congeladas", category: "Congelados", subcategory: "Preparados" },
  { name: "Empanadillas congeladas", category: "Congelados", subcategory: "Preparados" },
  { name: "San Jacobos", category: "Congelados", subcategory: "Preparados" },
  { name: "Gyozas congeladas", category: "Congelados", subcategory: "Preparados" },
  { name: "Rollitos de primavera", category: "Congelados", subcategory: "Preparados" },
  { name: "Masa de hojaldre congelada", category: "Congelados", subcategory: "Preparados" },
  { name: "Helado de vainilla", category: "Congelados", subcategory: "Helados" },
  { name: "Helado de chocolate", category: "Congelados", subcategory: "Helados" },
  { name: "Helado de fresa", category: "Congelados", subcategory: "Helados" },
  { name: "Polo de hielo", category: "Congelados", subcategory: "Helados" },
  { name: "Tarrina de helado", category: "Congelados", subcategory: "Helados" },
  { name: "Magnum", category: "Congelados", subcategory: "Helados", brand: "Magnum" },
  { name: "Cornetto", category: "Congelados", subcategory: "Helados", brand: "Cornetto" },
  { name: "Cubitos de hielo", category: "Congelados", subcategory: "Otros" },

  // ============================================
  // BEBIDAS
  // ============================================
  { name: "Agua mineral", category: "Bebidas", subcategory: "Aguas" },
  { name: "Agua con gas", category: "Bebidas", subcategory: "Aguas" },
  { name: "Agua sabor limón", category: "Bebidas", subcategory: "Aguas" },
  { name: "Zumo de naranja", category: "Bebidas", subcategory: "Zumos" },
  { name: "Zumo de manzana", category: "Bebidas", subcategory: "Zumos" },
  { name: "Zumo de piña", category: "Bebidas", subcategory: "Zumos" },
  { name: "Zumo de melocotón", category: "Bebidas", subcategory: "Zumos" },
  { name: "Zumo multifrutas", category: "Bebidas", subcategory: "Zumos" },
  { name: "Zumo de tomate", category: "Bebidas", subcategory: "Zumos" },
  { name: "Néctar de frutas", category: "Bebidas", subcategory: "Zumos" },
  { name: "Coca-Cola", category: "Bebidas", subcategory: "Refrescos", brand: "Coca-Cola" },
  { name: "Coca-Cola Zero", category: "Bebidas", subcategory: "Refrescos", brand: "Coca-Cola" },
  { name: "Pepsi", category: "Bebidas", subcategory: "Refrescos", brand: "Pepsi" },
  { name: "Fanta naranja", category: "Bebidas", subcategory: "Refrescos", brand: "Fanta" },
  { name: "Fanta limón", category: "Bebidas", subcategory: "Refrescos", brand: "Fanta" },
  { name: "Sprite", category: "Bebidas", subcategory: "Refrescos", brand: "Sprite" },
  { name: "7 Up", category: "Bebidas", subcategory: "Refrescos", brand: "7 Up" },
  { name: "Tónica", category: "Bebidas", subcategory: "Refrescos" },
  { name: "Bitter", category: "Bebidas", subcategory: "Refrescos" },
  { name: "Aquarius", category: "Bebidas", subcategory: "Refrescos", brand: "Aquarius" },
  { name: "Nestea", category: "Bebidas", subcategory: "Refrescos", brand: "Nestea" },
  { name: "Café molido", category: "Bebidas", subcategory: "Café" },
  { name: "Café en grano", category: "Bebidas", subcategory: "Café" },
  { name: "Café soluble", category: "Bebidas", subcategory: "Café" },
  { name: "Cápsulas de café", category: "Bebidas", subcategory: "Café" },
  { name: "Café descafeinado", category: "Bebidas", subcategory: "Café" },
  { name: "Té negro", category: "Bebidas", subcategory: "Té" },
  { name: "Té verde", category: "Bebidas", subcategory: "Té" },
  { name: "Té rooibos", category: "Bebidas", subcategory: "Té" },
  { name: "Manzanilla", category: "Bebidas", subcategory: "Infusiones" },
  { name: "Tila", category: "Bebidas", subcategory: "Infusiones" },
  { name: "Poleo menta", category: "Bebidas", subcategory: "Infusiones" },
  { name: "Infusión de jengibre", category: "Bebidas", subcategory: "Infusiones" },
  { name: "Cola Cao", category: "Bebidas", subcategory: "Cacao", brand: "Cola Cao" },
  { name: "Nesquik", category: "Bebidas", subcategory: "Cacao", brand: "Nesquik" },
  { name: "Cacao soluble", category: "Bebidas", subcategory: "Cacao" },
  { name: "Vino tinto", category: "Bebidas", subcategory: "Vinos" },
  { name: "Vino blanco", category: "Bebidas", subcategory: "Vinos" },
  { name: "Vino rosado", category: "Bebidas", subcategory: "Vinos" },
  { name: "Cava", category: "Bebidas", subcategory: "Vinos" },
  { name: "Cerveza", category: "Bebidas", subcategory: "Cervezas" },
  { name: "Cerveza sin alcohol", category: "Bebidas", subcategory: "Cervezas" },
  { name: "Cerveza artesana", category: "Bebidas", subcategory: "Cervezas" },
  { name: "Sidra", category: "Bebidas", subcategory: "Otros" },
  { name: "Sangría", category: "Bebidas", subcategory: "Otros" },
  { name: "Vermut", category: "Bebidas", subcategory: "Otros" },

  // ============================================
  // COMIDA PREPARADA
  // ============================================
  
  // Platos preparados refrigerados
  { name: "Ensalada preparada", category: "Comida Preparada", subcategory: "Ensaladas" },
  { name: "Ensalada César", category: "Comida Preparada", subcategory: "Ensaladas" },
  { name: "Ensalada de pasta", category: "Comida Preparada", subcategory: "Ensaladas" },
  { name: "Ensaladilla rusa", category: "Comida Preparada", subcategory: "Ensaladas" },
  { name: "Gazpacho fresco", category: "Comida Preparada", subcategory: "Sopas" },
  { name: "Salmorejo fresco", category: "Comida Preparada", subcategory: "Sopas" },
  { name: "Sopa fría", category: "Comida Preparada", subcategory: "Sopas" },
  { name: "Tortilla de patata", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Croquetas frescas", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Empanadas", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Pollo asado", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Canelones frescos", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Lasaña fresca", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Pasta fresca rellena", category: "Comida Preparada", subcategory: "Pasta fresca" },
  { name: "Raviolis frescos", category: "Comida Preparada", subcategory: "Pasta fresca" },
  { name: "Tortellini frescos", category: "Comida Preparada", subcategory: "Pasta fresca" },
  { name: "Ñoquis frescos", category: "Comida Preparada", subcategory: "Pasta fresca" },
  { name: "Espaguetis frescos", category: "Comida Preparada", subcategory: "Pasta fresca" },
  { name: "Tagliatelle frescos", category: "Comida Preparada", subcategory: "Pasta fresca" },
  
  // Sushi y comida asiática
  { name: "Bandeja de sushi", category: "Comida Preparada", subcategory: "Asiática" },
  { name: "Sushi variado", category: "Comida Preparada", subcategory: "Asiática" },
  { name: "Maki", category: "Comida Preparada", subcategory: "Asiática" },
  { name: "Nigiri", category: "Comida Preparada", subcategory: "Asiática" },
  { name: "Sashimi", category: "Comida Preparada", subcategory: "Asiática" },
  { name: "Poke bowl", category: "Comida Preparada", subcategory: "Asiática" },
  { name: "Gyozas frescas", category: "Comida Preparada", subcategory: "Asiática" },
  { name: "Rollitos de primavera frescos", category: "Comida Preparada", subcategory: "Asiática" },
  { name: "Wok de verduras", category: "Comida Preparada", subcategory: "Asiática" },
  { name: "Arroz tres delicias", category: "Comida Preparada", subcategory: "Asiática" },
  
  // Pizzas frescas
  { name: "Pizza fresca", category: "Comida Preparada", subcategory: "Pizzas" },
  { name: "Pizza margarita fresca", category: "Comida Preparada", subcategory: "Pizzas" },
  { name: "Pizza 4 quesos fresca", category: "Comida Preparada", subcategory: "Pizzas" },
  { name: "Pizza jamón y queso fresca", category: "Comida Preparada", subcategory: "Pizzas" },
  { name: "Pizza barbacoa fresca", category: "Comida Preparada", subcategory: "Pizzas" },
  { name: "Pizza vegetal fresca", category: "Comida Preparada", subcategory: "Pizzas" },
  { name: "Base de pizza fresca", category: "Comida Preparada", subcategory: "Pizzas" },
  
  // Sandwiches y bocadillos
  { name: "Sandwich mixto", category: "Comida Preparada", subcategory: "Sándwiches" },
  { name: "Sandwich vegetal", category: "Comida Preparada", subcategory: "Sándwiches" },
  { name: "Bocadillo de jamón", category: "Comida Preparada", subcategory: "Sándwiches" },
  { name: "Wrap de pollo", category: "Comida Preparada", subcategory: "Sándwiches" },
  { name: "Wrap vegetal", category: "Comida Preparada", subcategory: "Sándwiches" },
  
  // Tapas y aperitivos
  { name: "Aceitunas aliñadas", category: "Comida Preparada", subcategory: "Tapas" },
  { name: "Banderillas", category: "Comida Preparada", subcategory: "Tapas" },
  { name: "Patatas bravas", category: "Comida Preparada", subcategory: "Tapas" },
  { name: "Calamares a la romana", category: "Comida Preparada", subcategory: "Tapas" },
  { name: "Gambas al ajillo", category: "Comida Preparada", subcategory: "Tapas" },
  { name: "Tabla de quesos", category: "Comida Preparada", subcategory: "Tapas" },
  { name: "Tabla de embutidos", category: "Comida Preparada", subcategory: "Tapas" },

  // ============================================
  // DROGUERÍA (Limpieza, higiene, hogar)
  // ============================================
  
  // Limpieza del hogar
  { name: "Lavavajillas", category: "Droguería", subcategory: "Limpieza" },
  { name: "Pastillas lavavajillas", category: "Droguería", subcategory: "Limpieza" },
  { name: "Abrillantador lavavajillas", category: "Droguería", subcategory: "Limpieza" },
  { name: "Sal lavavajillas", category: "Droguería", subcategory: "Limpieza" },
  { name: "Detergente lavadora", category: "Droguería", subcategory: "Limpieza" },
  { name: "Detergente líquido", category: "Droguería", subcategory: "Limpieza" },
  { name: "Detergente en cápsulas", category: "Droguería", subcategory: "Limpieza" },
  { name: "Suavizante", category: "Droguería", subcategory: "Limpieza" },
  { name: "Quitamanchas", category: "Droguería", subcategory: "Limpieza" },
  { name: "Lejía", category: "Droguería", subcategory: "Limpieza" },
  { name: "Limpiador multiusos", category: "Droguería", subcategory: "Limpieza" },
  { name: "Limpiacristales", category: "Droguería", subcategory: "Limpieza" },
  { name: "Fregasuelos", category: "Droguería", subcategory: "Limpieza" },
  { name: "Limpia baños", category: "Droguería", subcategory: "Limpieza" },
  { name: "Limpia hornos", category: "Droguería", subcategory: "Limpieza" },
  { name: "Desengrasante", category: "Droguería", subcategory: "Limpieza" },
  { name: "Antical", category: "Droguería", subcategory: "Limpieza" },
  { name: "Limpiador de acero inoxidable", category: "Droguería", subcategory: "Limpieza" },
  { name: "Ambientador", category: "Droguería", subcategory: "Limpieza" },
  { name: "Ambientador en spray", category: "Droguería", subcategory: "Limpieza" },
  { name: "Desatascador", category: "Droguería", subcategory: "Limpieza" },
  { name: "Insecticida", category: "Droguería", subcategory: "Limpieza" },
  
  // Utensilios de limpieza
  { name: "Estropajo", category: "Droguería", subcategory: "Utensilios" },
  { name: "Estropajo con esponja", category: "Droguería", subcategory: "Utensilios" },
  { name: "Bayetas", category: "Droguería", subcategory: "Utensilios" },
  { name: "Bayeta microfibra", category: "Droguería", subcategory: "Utensilios" },
  { name: "Guantes de goma", category: "Droguería", subcategory: "Utensilios" },
  { name: "Fregona", category: "Droguería", subcategory: "Utensilios" },
  { name: "Recambio fregona", category: "Droguería", subcategory: "Utensilios" },
  { name: "Escoba", category: "Droguería", subcategory: "Utensilios" },
  { name: "Recogedor", category: "Droguería", subcategory: "Utensilios" },
  { name: "Mopa", category: "Droguería", subcategory: "Utensilios" },
  { name: "Cepillo WC", category: "Droguería", subcategory: "Utensilios" },
  
  // Papel y desechables
  { name: "Papel higiénico", category: "Droguería", subcategory: "Papel" },
  { name: "Papel de cocina", category: "Droguería", subcategory: "Papel" },
  { name: "Servilletas", category: "Droguería", subcategory: "Papel" },
  { name: "Pañuelos de papel", category: "Droguería", subcategory: "Papel" },
  { name: "Bolsas de basura", category: "Droguería", subcategory: "Papel" },
  { name: "Bolsas de basura reciclaje", category: "Droguería", subcategory: "Papel" },
  { name: "Papel de aluminio", category: "Droguería", subcategory: "Papel" },
  { name: "Film transparente", category: "Droguería", subcategory: "Papel" },
  { name: "Papel de horno", category: "Droguería", subcategory: "Papel" },
  
  // Higiene personal
  { name: "Jabón de manos", category: "Droguería", subcategory: "Higiene" },
  { name: "Jabón líquido", category: "Droguería", subcategory: "Higiene" },
  { name: "Gel de ducha", category: "Droguería", subcategory: "Higiene" },
  { name: "Gel hidroalcohólico", category: "Droguería", subcategory: "Higiene" },
  { name: "Champú", category: "Droguería", subcategory: "Higiene" },
  { name: "Champú anticaspa", category: "Droguería", subcategory: "Higiene" },
  { name: "Acondicionador", category: "Droguería", subcategory: "Higiene" },
  { name: "Mascarilla capilar", category: "Droguería", subcategory: "Higiene" },
  { name: "Pasta de dientes", category: "Droguería", subcategory: "Higiene" },
  { name: "Cepillo de dientes", category: "Droguería", subcategory: "Higiene" },
  { name: "Enjuague bucal", category: "Droguería", subcategory: "Higiene" },
  { name: "Hilo dental", category: "Droguería", subcategory: "Higiene" },
  { name: "Desodorante", category: "Droguería", subcategory: "Higiene" },
  { name: "Desodorante en spray", category: "Droguería", subcategory: "Higiene" },
  { name: "Crema hidratante", category: "Droguería", subcategory: "Higiene" },
  { name: "Crema de manos", category: "Droguería", subcategory: "Higiene" },
  { name: "Protector solar", category: "Droguería", subcategory: "Higiene" },
  { name: "After sun", category: "Droguería", subcategory: "Higiene" },
  { name: "Maquinillas de afeitar", category: "Droguería", subcategory: "Higiene" },
  { name: "Espuma de afeitar", category: "Droguería", subcategory: "Higiene" },
  { name: "Cuchillas de afeitar", category: "Droguería", subcategory: "Higiene" },
  { name: "Bastoncillos", category: "Droguería", subcategory: "Higiene" },
  { name: "Algodón", category: "Droguería", subcategory: "Higiene" },
  { name: "Compresas", category: "Droguería", subcategory: "Higiene" },
  { name: "Tampones", category: "Droguería", subcategory: "Higiene" },
  { name: "Toallitas íntimas", category: "Droguería", subcategory: "Higiene" },
  
  // Mascotas
  { name: "Pienso para perro", category: "Droguería", subcategory: "Mascotas" },
  { name: "Pienso para gato", category: "Droguería", subcategory: "Mascotas" },
  { name: "Comida húmeda para perro", category: "Droguería", subcategory: "Mascotas" },
  { name: "Comida húmeda para gato", category: "Droguería", subcategory: "Mascotas" },
  { name: "Arena para gato", category: "Droguería", subcategory: "Mascotas" },
  { name: "Snacks para perro", category: "Droguería", subcategory: "Mascotas" },
  { name: "Snacks para gato", category: "Droguería", subcategory: "Mascotas" },

  // ============================================
  // OTROS (Snacks, bebés, hogar general)
  // ============================================
  { name: "Pilas", category: "Otros", subcategory: "Hogar" },
  { name: "Bombillas", category: "Otros", subcategory: "Hogar" },
  { name: "Velas", category: "Otros", subcategory: "Hogar" },
  { name: "Cerillas", category: "Otros", subcategory: "Hogar" },
  { name: "Mechero", category: "Otros", subcategory: "Hogar" },

  // Snacks
  { name: "Patatas fritas de bolsa", category: "Otros", subcategory: "Snacks" },
  { name: "Nachos", category: "Otros", subcategory: "Snacks" },
  { name: "Palomitas de maíz", category: "Otros", subcategory: "Snacks" },
  { name: "Galletas María", category: "Otros", subcategory: "Snacks" },
  { name: "Galletas digestive", category: "Otros", subcategory: "Snacks" },
  { name: "Galletas de chocolate", category: "Otros", subcategory: "Snacks" },
  { name: "Oreo", category: "Otros", subcategory: "Snacks", brand: "Oreo" },
  { name: "Galletas integrales", category: "Otros", subcategory: "Snacks" },
  { name: "Barritas de cereales", category: "Otros", subcategory: "Snacks" },
  { name: "Chocolate en tableta", category: "Otros", subcategory: "Snacks" },
  { name: "Bombones", category: "Otros", subcategory: "Snacks" },
  { name: "Gominolas", category: "Otros", subcategory: "Snacks" },
  { name: "Regaliz", category: "Otros", subcategory: "Snacks" },
  { name: "Chicles", category: "Otros", subcategory: "Snacks" },
  { name: "Caramelos", category: "Otros", subcategory: "Snacks" },

  // Productos para bebés
  { name: "Pañales", category: "Otros", subcategory: "Bebés" },
  { name: "Toallitas húmedas", category: "Otros", subcategory: "Bebés" },
  { name: "Potitos", category: "Otros", subcategory: "Bebés" },
  { name: "Leche de fórmula", category: "Otros", subcategory: "Bebés" },
  { name: "Papilla de cereales", category: "Otros", subcategory: "Bebés" },
];

// Helper function to normalize text (remove accents and convert to lowercase)
function normalizeText(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim();
}

// Helper function to search products
export function searchGroceries(query: string, limit: number = 20): GroceryProduct[] {
  const normalizedQuery = normalizeText(query);
  
  if (!normalizedQuery) return [];
  
  // Split query into words for better matching
  const queryWords = normalizedQuery.split(/\s+/);
  
  return spanishGroceries
    .filter((product) => {
      const normalizedName = normalizeText(product.name);
      const normalizedCategory = normalizeText(product.category);
      const normalizedSubcategory = normalizeText(product.subcategory || "");
      const normalizedBrand = normalizeText(product.brand || "");
      
      // Check if all query words are found in the product name, category, subcategory or brand
      return queryWords.every(
        (word) =>
          normalizedName.includes(word) ||
          normalizedCategory.includes(word) ||
          normalizedSubcategory.includes(word) ||
          normalizedBrand.includes(word)
      );
    })
    .slice(0, limit);
}

// Get products by category
export function getProductsByCategory(category: string): GroceryProduct[] {
  return spanishGroceries.filter((product) => product.category === category);
}

// Get all subcategories for a category
export function getSubcategories(category: string): string[] {
  const subcategories = new Set<string>();
  spanishGroceries
    .filter((product) => product.category === category && product.subcategory)
    .forEach((product) => subcategories.add(product.subcategory!));
  return Array.from(subcategories).sort();
}

