/**
 * Additional Spanish supermarket products — merged into the main catalog.
 * Kept in a separate file to keep diffs manageable when expanding the database.
 */

export interface GroceryProductEntry {
  name: string;
  category: string;
  subcategory?: string;
  brand?: string;
}

export const spanishGroceriesExtra: GroceryProductEntry[] = [
  // ============================================
  // FRUTAS Y VERDURAS — más variedad
  // ============================================
  { name: "Tomate cherry amarillo", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Tomate negro", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Tomate seco", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Tomate verde", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Tomates en rama", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Pimiento asado", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Pimiento italiano", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Pimiento de Fresno", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Pimiento picante", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Chile serrano", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Chile habanero", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Berenjena baby", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Calabacín baby", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Calabaza butternut", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Calabaza Hokkaido", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Col rizada", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Pak choi", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Achicoria", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Cardo", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Brotes de soja", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Brotes de alfalfa", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Brotes de judía mungo", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Lechuga oak leaf", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Lechuga trocadero", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Mezcla de lechugas", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Mix de ensalada", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Champiñones shiitake", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Champiñones ostra", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Setas de cardo", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Setas de temporada", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Boletus", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Níscalos", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Colinabo", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Chirivía", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Apionabo", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Topinambur", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Judía plana", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Judía redonda", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Habas baby", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Guisantes baby", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Maíz baby", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Alcachofas baby", category: "Frutas y Verduras", subcategory: "Verduras" },
  { name: "Perejil", category: "Frutas y Verduras", subcategory: "Hierbas" },
  { name: "Cilantro", category: "Frutas y Verduras", subcategory: "Hierbas" },
  { name: "Albahaca", category: "Frutas y Verduras", subcategory: "Hierbas" },
  { name: "Menta", category: "Frutas y Verduras", subcategory: "Hierbas" },
  { name: "Estragón fresco", category: "Frutas y Verduras", subcategory: "Hierbas" },
  { name: "Mezcla de hierbas provenzales frescas", category: "Frutas y Verduras", subcategory: "Hierbas" },
  { name: "Physalis", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Grosellas", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Endrinas", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Brevas", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Paraguayo", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Platerina", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Pitaya", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Fruta de la pasión", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Carambola", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Mandarina satsuma", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Mandarina clementina", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Uva moscatel", category: "Frutas y Verduras", subcategory: "Frutas" },
  { name: "Uva red globe", category: "Frutas y Verduras", subcategory: "Frutas" },

  // ============================================
  // LÁCTEOS
  // ============================================
  { name: "Leche en polvo", category: "Lácteos", subcategory: "Leche" },
  { name: "Leche de cabra", category: "Lácteos", subcategory: "Leche" },
  { name: "Leche de oveja", category: "Lácteos", subcategory: "Leche" },
  { name: "Leche de pistacho", category: "Lácteos", subcategory: "Leche vegetal" },
  { name: "Leche de avellana", category: "Lácteos", subcategory: "Leche vegetal" },
  { name: "Bebida de avena", category: "Lácteos", subcategory: "Leche vegetal" },
  { name: "Nata para cocinar ligera", category: "Lácteos", subcategory: "Nata" },
  { name: "Nata agria", category: "Lácteos", subcategory: "Nata" },
  { name: "Crème fraîche", category: "Lácteos", subcategory: "Nata" },
  { name: "Yogur natural azucarado", category: "Lácteos", subcategory: "Yogures" },
  { name: "Yogur de coco", category: "Lácteos", subcategory: "Yogures" },
  { name: "Yogur de vainilla", category: "Lácteos", subcategory: "Yogures" },
  { name: "Yogur de mango", category: "Lácteos", subcategory: "Yogures" },
  { name: "Yogur de limón", category: "Lácteos", subcategory: "Yogures" },
  { name: "Yogur proteico", category: "Lácteos", subcategory: "Yogures" },
  { name: "Petit suisse", category: "Lácteos", subcategory: "Yogures" },
  { name: "Queso curado en aceite", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso de untar", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso provolone", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso pecorino", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso grana padano", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso roquefort", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso gorgonzola", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso halloumi", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso scamorza", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso de cabra curado", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso ahumado", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso en dados", category: "Lácteos", subcategory: "Quesos" },
  { name: "Queso fundido en lonchas", category: "Lácteos", subcategory: "Quesos" },
  { name: "Huevos XL", category: "Lácteos", subcategory: "Huevos" },
  { name: "Huevos L", category: "Lácteos", subcategory: "Huevos" },
  { name: "Huevos M", category: "Lácteos", subcategory: "Huevos" },
  { name: "Huevo", category: "Lácteos", subcategory: "Huevos" },
  { name: "Yema de huevo", category: "Lácteos", subcategory: "Huevos" },
  { name: "Leche merengada", category: "Lácteos", subcategory: "Postres lácteos" },
  { name: "Pudin de vainilla", category: "Lácteos", subcategory: "Postres lácteos" },
  { name: "Pudin de chocolate", category: "Lácteos", subcategory: "Postres lácteos" },
  { name: "Petit de chocolate", category: "Lácteos", subcategory: "Postres lácteos" },

  // ============================================
  // CARNES Y MARISCOS
  // ============================================
  { name: "Chistorra", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Longaniza", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Morcilla de cebolla", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Morcilla de Burgos", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Chorizo ibérico", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Chorizo para guisar", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Chorizo para cocido", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Salchichón ibérico", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Lomo ibérico", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Paleta ibérica", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Jamón ibérico de bellota", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Jamón ibérico cebo", category: "Carnes y Mariscos", subcategory: "Embutidos" },
  { name: "Lacón gallego", category: "Carnes y Mariscos", subcategory: "Cerdo" },
  { name: "Oreja de cerdo", category: "Carnes y Mariscos", subcategory: "Cerdo" },
  { name: "Manitas de cerdo", category: "Carnes y Mariscos", subcategory: "Cerdo" },
  { name: "Codillo de cerdo", category: "Carnes y Mariscos", subcategory: "Cerdo" },
  { name: "Papada ibérica", category: "Carnes y Mariscos", subcategory: "Cerdo" },
  { name: "Magro de cerdo", category: "Carnes y Mariscos", subcategory: "Cerdo" },
  { name: "Paletilla de cerdo", category: "Carnes y Mariscos", subcategory: "Cerdo" },
  { name: "Pierna de cerdo", category: "Carnes y Mariscos", subcategory: "Cerdo" },
  { name: "Callos", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Mollejas", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Hígado de ternera", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Riñones", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Lengua de ternera", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Jarrete de ternera", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Redondo de ternera", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Aguja de ternera", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Cadera de ternera", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Tira de ternera", category: "Carnes y Mariscos", subcategory: "Ternera" },
  { name: "Hamburguesa de pollo", category: "Carnes y Mariscos", subcategory: "Aves" },
  { name: "Hamburguesa vegetal", category: "Carnes y Mariscos", subcategory: "Aves" },
  { name: "Picadillo de pollo", category: "Carnes y Mariscos", subcategory: "Aves" },
  { name: "Magret de pato", category: "Carnes y Mariscos", subcategory: "Otros" },
  { name: "Pato entero", category: "Carnes y Mariscos", subcategory: "Otros" },
  { name: "Codorniz", category: "Carnes y Mariscos", subcategory: "Otros" },
  { name: "Liebre", category: "Carnes y Mariscos", subcategory: "Otros" },
  { name: "Jabalí", category: "Carnes y Mariscos", subcategory: "Otros" },
  { name: "Ciervo", category: "Carnes y Mariscos", subcategory: "Otros" },
  { name: "Caballa fresca", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Jurel", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Corvina", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Gallineta", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Mero", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Cherne", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Fletán", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Lenguado salvaje", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Besugo", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Pargo", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Rodaballo salvaje", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Anguila", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Angulas", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Arenque", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Arenque ahumado", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Sardina ahumada", category: "Carnes y Mariscos", subcategory: "Pescados" },
  { name: "Ostras", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Zamburiñas", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Navajas", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Carabineros", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Quisquilla", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Buey de mar", category: "Carnes y Mariscos", subcategory: "Mariscos" },
  { name: "Erizos de mar", category: "Carnes y Mariscos", subcategory: "Mariscos" },

  // ============================================
  // PANADERÍA
  // ============================================
  { name: "Pan de cristal", category: "Panadería", subcategory: "Pan" },
  { name: "Pan de masa madre", category: "Panadería", subcategory: "Pan" },
  { name: "Pan de espelta", category: "Panadería", subcategory: "Pan" },
  { name: "Pan de kamut", category: "Panadería", subcategory: "Pan" },
  { name: "Pan de cereales", category: "Panadería", subcategory: "Pan" },
  { name: "Pan de semillas", category: "Panadería", subcategory: "Pan" },
  { name: "Pan de ajo", category: "Panadería", subcategory: "Pan" },
  { name: "Pan de cebolla", category: "Panadería", subcategory: "Pan" },
  { name: "Focaccia", category: "Panadería", subcategory: "Pan" },
  { name: "Ciabatta", category: "Panadería", subcategory: "Pan" },
  { name: "Brioche", category: "Panadería", subcategory: "Bollería" },
  { name: "Brioche de chocolate", category: "Panadería", subcategory: "Bollería" },
  { name: "Caracolas", category: "Panadería", subcategory: "Bollería" },
  { name: "Ensaimada de Mallorca", category: "Panadería", subcategory: "Bollería" },
  { name: "Hojaldre", category: "Panadería", subcategory: "Bollería" },
  { name: "Rosquillas", category: "Panadería", subcategory: "Bollería" },
  { name: "Churros", category: "Panadería", subcategory: "Bollería" },
  { name: "Porras", category: "Panadería", subcategory: "Bollería" },
  { name: "Tortas de aceite", category: "Panadería", subcategory: "Bollería" },
  { name: "Mantecadas", category: "Panadería", subcategory: "Bollería" },
  { name: "Polvorones", category: "Panadería", subcategory: "Bollería" },
  { name: "Mazapanes", category: "Panadería", subcategory: "Bollería" },
  { name: "Turrón", category: "Panadería", subcategory: "Bollería" },
  { name: "Rosca de Reyes", category: "Panadería", subcategory: "Bollería" },
  { name: "Pan de leche", category: "Panadería", subcategory: "Pan" },
  { name: "Pan de viena", category: "Panadería", subcategory: "Pan" },
  { name: "Panecillo de leche", category: "Panadería", subcategory: "Pan" },

  // ============================================
  // DESPENSA — pasta, arroz, especias, conservas
  // ============================================
  { name: "Estrellitas", category: "Despensa", subcategory: "Pasta" },
  { name: "Coditos", category: "Despensa", subcategory: "Pasta" },
  { name: "Conchas", category: "Despensa", subcategory: "Pasta" },
  { name: "Caracoles", category: "Despensa", subcategory: "Pasta" },
  { name: "Espirales", category: "Despensa", subcategory: "Pasta" },
  { name: "Tiburones", category: "Despensa", subcategory: "Pasta" },
  { name: "Lazos", category: "Despensa", subcategory: "Pasta" },
  { name: "Pajaritas", category: "Despensa", subcategory: "Pasta" },
  { name: "Gnocchi", category: "Despensa", subcategory: "Pasta" },
  { name: "Spaghetti nº 5", category: "Despensa", subcategory: "Pasta" },
  { name: "Spaghetti nº 3", category: "Despensa", subcategory: "Pasta" },
  { name: "Bucatini", category: "Despensa", subcategory: "Pasta" },
  { name: "Rigatoni", category: "Despensa", subcategory: "Pasta" },
  { name: "Orecchiette", category: "Despensa", subcategory: "Pasta" },
  { name: "Pappardelle", category: "Despensa", subcategory: "Pasta" },
  { name: "Fideos para sopa", category: "Despensa", subcategory: "Pasta" },
  { name: "Fideos para fideuá", category: "Despensa", subcategory: "Pasta" },
  { name: "Fideos gruesos", category: "Despensa", subcategory: "Pasta" },
  { name: "Arroz calasparra", category: "Despensa", subcategory: "Arroz" },
  { name: "Arroz arborio", category: "Despensa", subcategory: "Arroz" },
  { name: "Arroz carnaroli", category: "Despensa", subcategory: "Arroz" },
  { name: "Arroz negro", category: "Despensa", subcategory: "Arroz" },
  { name: "Arroz para paella", category: "Despensa", subcategory: "Arroz" },
  { name: "Arroz tres delicias (seco)", category: "Despensa", subcategory: "Arroz" },
  { name: "Arroz con verduras (seco)", category: "Despensa", subcategory: "Arroz" },
  { name: "Arroz con leche (preparado)", category: "Despensa", subcategory: "Arroz" },
  { name: "Cuscús", category: "Despensa", subcategory: "Cereales" },
  { name: "Mijo", category: "Despensa", subcategory: "Cereales" },
  { name: "Amaranto", category: "Despensa", subcategory: "Cereales" },
  { name: "Espelta", category: "Despensa", subcategory: "Cereales" },
  { name: "Cebada", category: "Despensa", subcategory: "Cereales" },
  { name: "Harina de garbanzo", category: "Despensa", subcategory: "Harinas" },
  { name: "Harina de trigo sarraceno", category: "Despensa", subcategory: "Harinas" },
  { name: "Harina de coco", category: "Despensa", subcategory: "Harinas" },
  { name: "Harina de arroz", category: "Despensa", subcategory: "Harinas" },
  { name: "Harina de espelta", category: "Despensa", subcategory: "Harinas" },
  { name: "Almidón de patata", category: "Despensa", subcategory: "Harinas" },
  { name: "Fécula de patata", category: "Despensa", subcategory: "Harinas" },
  { name: "Tomate pelado entero", category: "Despensa", subcategory: "Conservas" },
  { name: "Tomate en dados", category: "Despensa", subcategory: "Conservas" },
  { name: "Tomate para sofrito", category: "Despensa", subcategory: "Conservas" },
  { name: "Sofrito de tomate y cebolla", category: "Despensa", subcategory: "Conservas" },
  { name: "Pisto", category: "Despensa", subcategory: "Conservas" },
  { name: "Pimientos asados en lata", category: "Despensa", subcategory: "Conservas" },
  { name: "Pimientos rellenos de atún", category: "Despensa", subcategory: "Conservas" },
  { name: "Pimientos rellenos de bacalao", category: "Despensa", subcategory: "Conservas" },
  { name: "Paté de atún", category: "Despensa", subcategory: "Conservas" },
  { name: "Paté de campaña", category: "Despensa", subcategory: "Conservas" },
  { name: "Paté de foie", category: "Despensa", subcategory: "Conservas" },
  { name: "Paté de sardinas", category: "Despensa", subcategory: "Conservas" },
  { name: "Paté de anchoas", category: "Despensa", subcategory: "Conservas" },
  { name: "Anchoas en salazón", category: "Despensa", subcategory: "Conservas" },
  { name: "Boquerones en vinagre", category: "Despensa", subcategory: "Conservas" },
  { name: "Caballa en tomate", category: "Despensa", subcategory: "Conservas" },
  { name: "Sardinas en tomate", category: "Despensa", subcategory: "Conservas" },
  { name: "Atún claro en aceite", category: "Despensa", subcategory: "Conservas" },
  { name: "Atún en tomate", category: "Despensa", subcategory: "Conservas" },
  { name: "Melva", category: "Despensa", subcategory: "Conservas" },
  { name: "Pulpo en aceite", category: "Despensa", subcategory: "Conservas" },
  { name: "Mejillones en escabeche picantes", category: "Despensa", subcategory: "Conservas" },
  { name: "Almejas en salsa verde", category: "Despensa", subcategory: "Conservas" },
  { name: "Setas en conserva", category: "Despensa", subcategory: "Conservas" },
  { name: "Trufa en conserva", category: "Despensa", subcategory: "Conservas" },
  { name: "Judías blancas en bote", category: "Despensa", subcategory: "Conservas" },
  { name: "Cocido montañés en bote", category: "Despensa", subcategory: "Conservas" },
  { name: "Fabada asturiana en bote", category: "Despensa", subcategory: "Conservas" },
  { name: "Callos en salsa", category: "Despensa", subcategory: "Conservas" },
  { name: "Menestra en conserva", category: "Despensa", subcategory: "Conservas" },
  { name: "Menestra de verduras", category: "Despensa", subcategory: "Conservas" },
  { name: "Salsa de pescado", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa de ostras", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa hoisin", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa de ciruela", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa agridulce", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa chimichurri", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa ranch", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa tártara", category: "Despensa", subcategory: "Salsas" },
  { name: "Vinagreta", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa romesco", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa mojo picón", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa mojo verde", category: "Despensa", subcategory: "Salsas" },
  { name: "Salsa bechamel", category: "Despensa", subcategory: "Salsas" },
  { name: "Bechamel en brick", category: "Despensa", subcategory: "Salsas" },
  { name: "Miso", category: "Despensa", subcategory: "Salsas" },
  { name: "Pasta de curry rojo", category: "Despensa", subcategory: "Salsas" },
  { name: "Pasta de curry verde", category: "Despensa", subcategory: "Salsas" },
  { name: "Leche de coco en lata", category: "Despensa", subcategory: "Salsas" },
  { name: "Crema de coco", category: "Despensa", subcategory: "Salsas" },
  { name: "Pimentón ahumado", category: "Despensa", subcategory: "Especias" },
  { name: "Pimentón picante de la Vera", category: "Despensa", subcategory: "Especias" },
  { name: "Azafrán en hebras", category: "Despensa", subcategory: "Especias" },
  { name: "Sazonador para paella", category: "Despensa", subcategory: "Especias" },
  { name: "Sazonador para fabada", category: "Despensa", subcategory: "Especias" },
  { name: "Pimienta rosa", category: "Despensa", subcategory: "Especias" },
  { name: "Pimienta verde", category: "Despensa", subcategory: "Especias" },
  { name: "Pimienta de Jamaica", category: "Despensa", subcategory: "Especias" },
  { name: "Pimienta de Sichuan", category: "Despensa", subcategory: "Especias" },
  { name: "Cardamomo", category: "Despensa", subcategory: "Especias" },
  { name: "Anís estrellado", category: "Despensa", subcategory: "Especias" },
  { name: "Semillas de hinojo", category: "Despensa", subcategory: "Especias" },
  { name: "Semillas de comino", category: "Despensa", subcategory: "Especias" },
  { name: "Semillas de cilantro", category: "Despensa", subcategory: "Especias" },
  { name: "Sumac", category: "Despensa", subcategory: "Especias" },
  { name: "Za'atar", category: "Despensa", subcategory: "Especias" },
  { name: "Wasabi en polvo", category: "Despensa", subcategory: "Especias" },
  { name: "Jengibre en polvo", category: "Despensa", subcategory: "Especias" },
  { name: "Cúrcuma fresca en polvo", category: "Despensa", subcategory: "Especias" },
  { name: "Mezcla para paella", category: "Despensa", subcategory: "Especias" },
  { name: "Mezcla para guisos", category: "Despensa", subcategory: "Especias" },
  { name: "Mezcla 5 especias", category: "Despensa", subcategory: "Especias" },
  { name: "Garam masala", category: "Despensa", subcategory: "Especias" },
  { name: "Ras el hanout", category: "Despensa", subcategory: "Especias" },
  { name: "Vinagre de arroz", category: "Despensa", subcategory: "Vinagres" },
  { name: "Vinagre de vino blanco", category: "Despensa", subcategory: "Vinagres" },
  { name: "Vinagre de vino tinto", category: "Despensa", subcategory: "Vinagres" },
  { name: "Aceite de trufa", category: "Despensa", subcategory: "Aceites" },
  { name: "Aceite de oliva virgen extra spray", category: "Despensa", subcategory: "Aceites" },
  { name: "Aceite para freír", category: "Despensa", subcategory: "Aceites" },
  { name: "Manteca de cerdo", category: "Despensa", subcategory: "Aceites" },
  { name: "Grasa de pato", category: "Despensa", subcategory: "Aceites" },
  { name: "Caldo casero de pollo", category: "Despensa", subcategory: "Caldos" },
  { name: "Caldo casero de verduras", category: "Despensa", subcategory: "Caldos" },
  { name: "Caldo de pescado concentrado", category: "Despensa", subcategory: "Caldos" },
  { name: "Fumet de pescado", category: "Despensa", subcategory: "Caldos" },
  { name: "Brick de caldo", category: "Despensa", subcategory: "Caldos" },
  { name: "Crema de verduras", category: "Despensa", subcategory: "Caldos" },
  { name: "Crema de calabaza", category: "Despensa", subcategory: "Caldos" },
  { name: "Crema de tomate", category: "Despensa", subcategory: "Caldos" },
  { name: "Puré de patata en copos", category: "Despensa", subcategory: "Caldos" },
  { name: "Puré de patata instantáneo", category: "Despensa", subcategory: "Caldos" },
  { name: "Mermelada de tomate", category: "Despensa", subcategory: "Cremas" },
  { name: "Mermelada de higo", category: "Despensa", subcategory: "Cremas" },
  { name: "Mermelada de ciruela", category: "Despensa", subcategory: "Cremas" },
  { name: "Confitura de frutos rojos", category: "Despensa", subcategory: "Cremas" },
  { name: "Crema de avellanas", category: "Despensa", subcategory: "Cremas" },
  { name: "Crema de almendras", category: "Despensa", subcategory: "Cremas" },
  { name: "Tahini de sésamo", category: "Despensa", subcategory: "Cremas" },
  { name: "Tortitas de arroz", category: "Despensa", subcategory: "Cereales" },
  { name: "Tortitas de maíz", category: "Despensa", subcategory: "Cereales" },
  { name: "Galletas de arroz", category: "Despensa", subcategory: "Cereales" },
  { name: "Pan de molde tostado", category: "Despensa", subcategory: "Cereales" },
  { name: "Salvado de avena", category: "Despensa", subcategory: "Cereales" },
  { name: "Avena instantánea", category: "Despensa", subcategory: "Cereales" },
  { name: "Chocolate para postres", category: "Despensa", subcategory: "Repostería" },
  { name: "Cobertura de chocolate", category: "Despensa", subcategory: "Repostería" },
  { name: "Fondant", category: "Despensa", subcategory: "Repostería" },
  { name: "Colorante en gel", category: "Despensa", subcategory: "Repostería" },
  { name: "Sprinkles", category: "Despensa", subcategory: "Repostería" },
  { name: "Azúcar moreno de caña", category: "Despensa", subcategory: "Repostería" },
  { name: "Stevia", category: "Despensa", subcategory: "Repostería" },
  { name: "Eritritol", category: "Despensa", subcategory: "Repostería" },
  { name: "Agave en polvo", category: "Despensa", subcategory: "Repostería" },
  { name: "Levadura nutricional", category: "Despensa", subcategory: "Repostería" },
  { name: "Agar agar", category: "Despensa", subcategory: "Repostería" },
  { name: "Pectina", category: "Despensa", subcategory: "Repostería" },
  { name: "Coco en trocitos", category: "Despensa", subcategory: "Frutos secos" },
  { name: "Macadamias", category: "Despensa", subcategory: "Frutos secos" },
  { name: "Nueces de Brasil", category: "Despensa", subcategory: "Frutos secos" },
  { name: "Pecanas", category: "Despensa", subcategory: "Frutos secos" },
  { name: "Mix de semillas", category: "Despensa", subcategory: "Semillas" },
  { name: "Hummus de remolacha", category: "Despensa", subcategory: "Salsas" },
  { name: "Hummus de aguacate", category: "Despensa", subcategory: "Salsas" },

  // ============================================
  // CONGELADOS
  // ============================================
  { name: "Acelgas congeladas", category: "Congelados", subcategory: "Verduras" },
  { name: "Coliflor congelada", category: "Congelados", subcategory: "Verduras" },
  { name: "Col kale congelada", category: "Congelados", subcategory: "Verduras" },
  { name: "Verduras para wok", category: "Congelados", subcategory: "Verduras" },
  { name: "Verduras para guisar", category: "Congelados", subcategory: "Verduras" },
  { name: "Verduras para paella", category: "Congelados", subcategory: "Verduras" },
  { name: "Aros de cebolla congelados", category: "Congelados", subcategory: "Verduras" },
  { name: "Palitos de mozzarella", category: "Congelados", subcategory: "Preparados" },
  { name: "Tequeños", category: "Congelados", subcategory: "Preparados" },
  { name: "Patatas bravas congeladas", category: "Congelados", subcategory: "Preparados" },
  { name: "Croquetas de jamón", category: "Congelados", subcategory: "Preparados" },
  { name: "Croquetas de pollo", category: "Congelados", subcategory: "Preparados" },
  { name: "Croquetas de bacalao", category: "Congelados", subcategory: "Preparados" },
  { name: "Croquetas de setas", category: "Congelados", subcategory: "Preparados" },
  { name: "Albóndigas congeladas", category: "Congelados", subcategory: "Preparados" },
  { name: "Paella congelada", category: "Congelados", subcategory: "Preparados" },
  { name: "Fabada congelada", category: "Congelados", subcategory: "Preparados" },
  { name: "Lentejas congeladas", category: "Congelados", subcategory: "Preparados" },
  { name: "Gazpacho congelado", category: "Congelados", subcategory: "Preparados" },
  { name: "Salmón congelado", category: "Congelados", subcategory: "Pescados" },
  { name: "Dorada congelada", category: "Congelados", subcategory: "Pescados" },
  { name: "Lubina congelada", category: "Congelados", subcategory: "Pescados" },
  { name: "Pescado del día congelado", category: "Congelados", subcategory: "Pescados" },
  { name: "Rabas congeladas", category: "Congelados", subcategory: "Pescados" },
  { name: "Pulpo cocido congelado", category: "Congelados", subcategory: "Pescados" },
  { name: "Helado de pistacho", category: "Congelados", subcategory: "Helados" },
  { name: "Helado de limón", category: "Congelados", subcategory: "Helados" },
  { name: "Helado de stracciatella", category: "Congelados", subcategory: "Helados" },
  { name: "Sandwich de helado", category: "Congelados", subcategory: "Helados" },

  // ============================================
  // BEBIDAS
  // ============================================
  { name: "Agua con sabores", category: "Bebidas", subcategory: "Aguas" },
  { name: "Agua con gas sabor lima limón", category: "Bebidas", subcategory: "Aguas" },
  { name: "Zumo de pomelo", category: "Bebidas", subcategory: "Zumos" },
  { name: "Zumo de granada", category: "Bebidas", subcategory: "Zumos" },
  { name: "Zumo de zanahoria", category: "Bebidas", subcategory: "Zumos" },
  { name: "Zumo de remolacha", category: "Bebidas", subcategory: "Zumos" },
  { name: "Zumo de arándanos", category: "Bebidas", subcategory: "Zumos" },
  { name: "Zumo de uva", category: "Bebidas", subcategory: "Zumos" },
  { name: "Zumo de pera", category: "Bebidas", subcategory: "Zumos" },
  { name: "Zumo de mango", category: "Bebidas", subcategory: "Zumos" },
  { name: "Zumo de aloe vera", category: "Bebidas", subcategory: "Zumos" },
  { name: "Zumo de coco", category: "Bebidas", subcategory: "Zumos" },
  { name: "Mosto de uva", category: "Bebidas", subcategory: "Zumos" },
  { name: "Horchata", category: "Bebidas", subcategory: "Zumos" },
  { name: "Granizado de limón", category: "Bebidas", subcategory: "Refrescos" },
  { name: "Granizado de café", category: "Bebidas", subcategory: "Refrescos" },
  { name: "Kombucha", category: "Bebidas", subcategory: "Refrescos" },
  { name: "Bebida isotónica", category: "Bebidas", subcategory: "Refrescos" },
  { name: "Bebida energética", category: "Bebidas", subcategory: "Refrescos" },
  { name: "Red Bull", category: "Bebidas", subcategory: "Refrescos", brand: "Red Bull" },
  { name: "Monster", category: "Bebidas", subcategory: "Refrescos", brand: "Monster" },
  { name: "Schweppes", category: "Bebidas", subcategory: "Refrescos", brand: "Schweppes" },
  { name: "Ginger ale", category: "Bebidas", subcategory: "Refrescos" },
  { name: "Limonada", category: "Bebidas", subcategory: "Refrescos" },
  { name: "Batido de chocolate", category: "Bebidas", subcategory: "Lácteos" },
  { name: "Batido de fresa", category: "Bebidas", subcategory: "Lácteos" },
  { name: "Batido de vainilla", category: "Bebidas", subcategory: "Lácteos" },
  { name: "Batido proteico", category: "Bebidas", subcategory: "Lácteos" },
  { name: "Café descafeinado en grano", category: "Bebidas", subcategory: "Café" },
  { name: "Café molido natural", category: "Bebidas", subcategory: "Café" },
  { name: "Café molido mezcla", category: "Bebidas", subcategory: "Café" },
  { name: "Café molido fuerte", category: "Bebidas", subcategory: "Café" },
  { name: "Café de especialidad", category: "Bebidas", subcategory: "Café" },
  { name: "Café cold brew", category: "Bebidas", subcategory: "Café" },
  { name: "Té matcha", category: "Bebidas", subcategory: "Té" },
  { name: "Té chai", category: "Bebidas", subcategory: "Té" },
  { name: "Té blanco", category: "Bebidas", subcategory: "Té" },
  { name: "Infusión de frutos rojos", category: "Bebidas", subcategory: "Infusiones" },
  { name: "Infusión digestiva", category: "Bebidas", subcategory: "Infusiones" },
  { name: "Infusión relajante", category: "Bebidas", subcategory: "Infusiones" },
  { name: "Vino tinto crianza", category: "Bebidas", subcategory: "Vinos" },
  { name: "Vino tinto reserva", category: "Bebidas", subcategory: "Vinos" },
  { name: "Vino tinto joven", category: "Bebidas", subcategory: "Vinos" },
  { name: "Vino tinto Rioja", category: "Bebidas", subcategory: "Vinos" },
  { name: "Vino tinto Ribera", category: "Bebidas", subcategory: "Vinos" },
  { name: "Vino blanco albariño", category: "Bebidas", subcategory: "Vinos" },
  { name: "Vino blanco verdejo", category: "Bebidas", subcategory: "Vinos" },
  { name: "Vino dulce", category: "Bebidas", subcategory: "Vinos" },
  { name: "Vino de Oporto", category: "Bebidas", subcategory: "Vinos" },
  { name: "Jerez", category: "Bebidas", subcategory: "Vinos" },
  { name: "Brandy", category: "Bebidas", subcategory: "Otros" },
  { name: "Ginebra", category: "Bebidas", subcategory: "Otros" },
  { name: "Ron", category: "Bebidas", subcategory: "Otros" },
  { name: "Vodka", category: "Bebidas", subcategory: "Otros" },
  { name: "Whisky", category: "Bebidas", subcategory: "Otros" },
  { name: "Licor de hierbas", category: "Bebidas", subcategory: "Otros" },
  { name: "Pacharán", category: "Bebidas", subcategory: "Otros" },
  { name: "Orujo", category: "Bebidas", subcategory: "Otros" },
  { name: "Cerveza de trigo", category: "Bebidas", subcategory: "Cervezas" },
  { name: "Cerveza negra", category: "Bebidas", subcategory: "Cervezas" },
  { name: "Cerveza IPA", category: "Bebidas", subcategory: "Cervezas" },
  { name: "Cerveza sin gluten", category: "Bebidas", subcategory: "Cervezas" },
  { name: "Radler", category: "Bebidas", subcategory: "Cervezas" },
  { name: "Clara con limón", category: "Bebidas", subcategory: "Cervezas" },

  // ============================================
  // COMIDA PREPARADA
  // ============================================
  { name: "Fabada", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Cocido madrileño", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Lentejas estofadas", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Garbanzos con espinacas", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Albóndigas en salsa", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Estofado de ternera", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Rabo de toro guisado", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Paella valenciana", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Paella de marisco", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Arroz negro", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Fideuá", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Pulpo a la gallega", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Merluza en salsa verde", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Bacalao al pil pil", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Bacalao a la vizcaína", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Huevos rotos", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Revuelto de setas", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Revuelto de ajos tiernos", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Revuelto de espárragos", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Pisto manchego", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Escalivada", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Zarangollo", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Berenjenas rellenas", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Pimientos rellenos", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Calamares rellenos", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Musaka", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Curry de pollo", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Pad thai", category: "Comida Preparada", subcategory: "Asiática" },
  { name: "Noodles salteados", category: "Comida Preparada", subcategory: "Asiática" },
  { name: "Arroz frito", category: "Comida Preparada", subcategory: "Asiática" },
  { name: "Dumplings", category: "Comida Preparada", subcategory: "Asiática" },
  { name: "Bao buns", category: "Comida Preparada", subcategory: "Asiática" },
  { name: "Burrito", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Quesadilla", category: "Comida Preparada", subcategory: "Platos" },
  { name: "Nachos con queso", category: "Comida Preparada", subcategory: "Tapas" },
  { name: "Croquetas de jamón ibérico", category: "Comida Preparada", subcategory: "Tapas" },
  { name: "Pimientos de Padrón", category: "Comida Preparada", subcategory: "Tapas" },
  { name: "Boquerones fritos", category: "Comida Preparada", subcategory: "Tapas" },
  { name: "Chopitos", category: "Comida Preparada", subcategory: "Tapas" },
  { name: "Mejillones al vapor", category: "Comida Preparada", subcategory: "Tapas" },
  { name: "Almejas a la marinera", category: "Comida Preparada", subcategory: "Tapas" },

  // ============================================
  // DROGUERÍA
  // ============================================
  { name: "Sal para lavavajillas", category: "Droguería", subcategory: "Limpieza" },
  { name: "Aditivo lavavajillas", category: "Droguería", subcategory: "Limpieza" },
  { name: "Perlas de olor lavadora", category: "Droguería", subcategory: "Limpieza" },
  { name: "Toallitas para lavadora", category: "Droguería", subcategory: "Limpieza" },
  { name: "Quitamanchas en spray", category: "Droguería", subcategory: "Limpieza" },
  { name: "Blanqueador", category: "Droguería", subcategory: "Limpieza" },
  { name: "Limpiador de vitrocerámica", category: "Droguería", subcategory: "Limpieza" },
  { name: "Limpiador de acero", category: "Droguería", subcategory: "Limpieza" },
  { name: "Limpiador de muebles", category: "Droguería", subcategory: "Limpieza" },
  { name: "Cera para suelos", category: "Droguería", subcategory: "Limpieza" },
  { name: "Paños de microfibra", category: "Droguería", subcategory: "Utensilios" },
  { name: "Esponja verde", category: "Droguería", subcategory: "Utensilios" },
  { name: "Funda de almohada", category: "Droguería", subcategory: "Hogar" },
  { name: "Sábanas", category: "Droguería", subcategory: "Hogar" },
  { name: "Toalla de baño", category: "Droguería", subcategory: "Hogar" },
  { name: "Velas aromáticas", category: "Droguería", subcategory: "Hogar" },
  { name: "Incienso", category: "Droguería", subcategory: "Hogar" },
  { name: "Bastoncillos de algodón", category: "Droguería", subcategory: "Higiene" },
  { name: "Discos desmaquillantes", category: "Droguería", subcategory: "Higiene" },
  { name: "Agua micelar", category: "Droguería", subcategory: "Higiene" },
  { name: "Crema facial", category: "Droguería", subcategory: "Higiene" },
  { name: "Contorno de ojos", category: "Droguería", subcategory: "Higiene" },
  { name: "Bálsamo labial", category: "Droguería", subcategory: "Higiene" },
  { name: "Cepillo de dientes eléctrico", category: "Droguería", subcategory: "Higiene" },
  { name: "Recambios cepillo eléctrico", category: "Droguería", subcategory: "Higiene" },
  { name: "Cepillo de pelo", category: "Droguería", subcategory: "Higiene" },
  { name: "Peine", category: "Droguería", subcategory: "Higiene" },
  { name: "Laca para el pelo", category: "Droguería", subcategory: "Higiene" },
  { name: "Gel fijador", category: "Droguería", subcategory: "Higiene" },
  { name: "Espuma de baño", category: "Droguería", subcategory: "Higiene" },
  { name: "Sales de baño", category: "Droguería", subcategory: "Higiene" },
  { name: "Jabón de ducha", category: "Droguería", subcategory: "Higiene" },
  { name: "Jabón sólido", category: "Droguería", subcategory: "Higiene" },
  { name: "Crema de afeitar", category: "Droguería", subcategory: "Higiene" },
  { name: "After shave", category: "Droguería", subcategory: "Higiene" },
  { name: "Cera depilatoria", category: "Droguería", subcategory: "Higiene" },
  { name: "Cinta depilatoria", category: "Droguería", subcategory: "Higiene" },
  { name: "Maquinilla desechable", category: "Droguería", subcategory: "Higiene" },
  { name: "Papel de regalo", category: "Droguería", subcategory: "Papel" },
  { name: "Bolsas de congelación", category: "Droguería", subcategory: "Papel" },
  { name: "Film reutilizable", category: "Droguería", subcategory: "Papel" },
  { name: "Papel vegetal", category: "Droguería", subcategory: "Papel" },
  { name: "Bolsas de conservación", category: "Droguería", subcategory: "Papel" },

  // ============================================
  // OTROS
  // ============================================
  { name: "Tortitas de maíz sin sal", category: "Otros", subcategory: "Snacks" },
  { name: "Frutos secos salados", category: "Otros", subcategory: "Snacks" },
  { name: "Frutos secos sin sal", category: "Otros", subcategory: "Snacks" },
  { name: "Mix aperitivo", category: "Otros", subcategory: "Snacks" },
  { name: "Galletas saladas", category: "Otros", subcategory: "Snacks" },
  { name: "Crackers", category: "Otros", subcategory: "Snacks" },
  { name: "Picos integrales", category: "Otros", subcategory: "Snacks" },
  { name: "Palitos de pan", category: "Otros", subcategory: "Snacks" },
  { name: "Rosquilletas", category: "Otros", subcategory: "Snacks" },
  { name: "Pipas de girasol", category: "Otros", subcategory: "Snacks" },
  { name: "Pipas de calabaza", category: "Otros", subcategory: "Snacks" },
  { name: "Maíz para palomitas", category: "Otros", subcategory: "Snacks" },
  { name: "Galletas de avena", category: "Otros", subcategory: "Snacks" },
  { name: "Galletas de mantequilla", category: "Otros", subcategory: "Snacks" },
  { name: "Galletas de limón", category: "Otros", subcategory: "Snacks" },
  { name: "Galletas de coco", category: "Otros", subcategory: "Snacks" },
  { name: "Galletas de avena y chocolate", category: "Otros", subcategory: "Snacks" },
  { name: "Barrita de proteínas", category: "Otros", subcategory: "Snacks" },
  { name: "Barrita de cereales y chocolate", category: "Otros", subcategory: "Snacks" },
  { name: "Chocolate a la taza", category: "Otros", subcategory: "Snacks" },
  { name: "Cola Cao en polvo", category: "Otros", subcategory: "Snacks", brand: "Cola Cao" },
  { name: "Nesquik en polvo", category: "Otros", subcategory: "Snacks", brand: "Nesquik" },
  { name: "Turrones", category: "Otros", subcategory: "Snacks" },
  { name: "Mazapán", category: "Otros", subcategory: "Snacks" },
  { name: "Polvorón", category: "Otros", subcategory: "Snacks" },
  { name: "Roscos de vino", category: "Otros", subcategory: "Snacks" },
  { name: "Pilas AA", category: "Otros", subcategory: "Hogar" },
  { name: "Pilas AAA", category: "Otros", subcategory: "Hogar" },
  { name: "Pilas de botón", category: "Otros", subcategory: "Hogar" },
  { name: "Cargador USB", category: "Otros", subcategory: "Hogar" },
  { name: "Cable USB", category: "Otros", subcategory: "Hogar" },
  { name: "Fósforos", category: "Otros", subcategory: "Hogar" },
  { name: "Carbón vegetal", category: "Otros", subcategory: "Hogar" },
  { name: "Pastillas de encendido", category: "Otros", subcategory: "Hogar" },
  { name: "Bolsas de té", category: "Otros", subcategory: "Hogar" },
  { name: "Filtros de café", category: "Otros", subcategory: "Hogar" },
  { name: "Cápsulas compatibles Nespresso", category: "Otros", subcategory: "Hogar" },
  { name: "Cápsulas compatibles Dolce Gusto", category: "Otros", subcategory: "Hogar" },
  { name: "Gel de manos antibacteriano", category: "Otros", subcategory: "Hogar" },
  { name: "Crema solar", category: "Otros", subcategory: "Hogar" },
  { name: "Repelente de mosquitos", category: "Otros", subcategory: "Hogar" },
  { name: "Biberón", category: "Otros", subcategory: "Bebés" },
  { name: "Chupete", category: "Otros", subcategory: "Bebés" },
  { name: "Papillas de frutas", category: "Otros", subcategory: "Bebés" },
  { name: "Papillas de verduras", category: "Otros", subcategory: "Bebés" },
  { name: "Galletas para bebé", category: "Otros", subcategory: "Bebés" },
  { name: "Agua para biberón", category: "Otros", subcategory: "Bebés" },
  { name: "Arena para pájaros", category: "Droguería", subcategory: "Mascotas" },
  { name: "Pienso para pájaros", category: "Droguería", subcategory: "Mascotas" },
  { name: "Pienso para tortugas", category: "Droguería", subcategory: "Mascotas" },
  { name: "Snacks para hámster", category: "Droguería", subcategory: "Mascotas" },
  { name: "Lecho para roedores", category: "Droguería", subcategory: "Mascotas" },
];
